version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - cd infra
      - npm install
  build:
    commands:
      - npm run build
      - npx cdk synth
artifacts:
  base-directory: infra/cdk.out
  files:
    - '**/*'
