# Generated by Django 4.2.13 on 2024-06-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='other_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
