# Generated by Django 4.2.13 on 2024-06-16 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_homepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
