# Generated by Django 4.2.11 on 2024-04-21 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterField(
            model_name='phase',
            name='workstream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='yapp.workstream'),
        ),
        migrations.AlterField(
            model_name='workstream',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yapp.project'),
        ),
    ]
